IBM/video-streaming-developer-docs

- gatsby-config.js
- package.json
Updated the deploy script with the public github repo url
> chore(packagejson): update deploy script

- gatsby-config.js
- package.json
I updated repo related URLs in gatsby-config and package.json files after the public migration.
> fix: migration to public

- gatsby-config.js
Reverts IBM/video-streaming-developer-docs#10
> Revert "fix(gatsby-config): remove pathprefix"

- gatsby-config.js
Reverts IBM/video-streaming-developer-docs#11
> Revert "Revert "fix(gatsby-config): remove pathprefix""

- src/components/EmbedPlayer/Controls/multi.js
- src/pages/player-api-examples/multiview.mdx
From Mike:
perhaps we should put a comment in the code that says the user can override with custom images like that?
it just seems a little odd that we have an example on the page that doesn't follow the code that's written 1:1
> Multiview thumbs

- src/pages/channel-api-poll.mdx
- src/pages/channel-api-qna.mdx
- __Type:__
- 📚Docs
- __Ticket:__ [COBRA-2730](<https://issues.ustream-adm.in/browse/COBRA-2730>)
> docs(poll): poll export

- src/data/nav-items.yaml
> docs(poll): add Poll to nav

- src/pages/organization-api/administrators.mdx
- __Type:__
- 📚Docs
- __Ticket:__ [COBRA-2823](<https://issues.ustream-adm.in/browse/COBRA-2823>)
> docs(organization): URLs and channel search

- src/pages/organization-api/administrators.mdx
- __Type:__
- 🐛Fix
- __Ticket:__ [COBRA-2917](<https://issues.ustream-adm.in/browse/COBRA-2917>)
Missing error response.
> fix(organization): add missing error

- src/data/nav-items.yaml
- src/pages/channel-api-live-cta.mdx
> docs: added Live CTA API

- src/pages/channel-api-events.mdx
- __Type:__
- 📚 Docs
- __Ticket:__ [PROJCAT-503](<https://issues.ustream-adm.in/browse/PROJCAT-503>)
As a customer, I should be able to create, update, delete and list events through the Channel API.
Site backend updated the Events API with create, list, update and delete functionality.
> docs(channel-api): update event api

- README.md
- __Type:__
- ♻️Chore
readme cleanup.
> chore(readme): remove under-construction emojis

- README.md
- __Type:__
- ♻️Chore
travis-ci.org is really slow, so I created new integration on travis-ci.com, hopes its faster.
> chore: trigger new travis-ci.com build hopes its faster

- src/pages/organization-api/administrators.mdx
- __Type:__
- 🐛Fix
- __Ticket:__ [COBRA-2917](<https://issues.ustream-adm.in/browse/COBRA-2917>)
> fix(organization): channel level update fix

- src/pages/channel-api-playlists/create-and-manage-playlists.mdx
- __Type:__
-✨Fix
- __Ticket:__ [CORE-2642](<https://issues.ustream-adm.in/browse/CORE-2642>)
_Typo in "Delete a playlist" API documentation_
> feat(playlist): core-2642 Typo in "Delete a playlist" API documentation

- src/pages/organization-api/administrators.mdx
> fix(organization): title typo

- src/pages/organization-api/administrators.mdx
- __Type:__
- 🐛Fix
- __Ticket:__ [COBRA-3004](<https://issues.ustream-adm.in/browse/COBRA-3004>)
> fix(organization): COBRA-3004

- src/pages/broadcaster-sdk-android/getting-started.mdx
- src/pages/player-sdk-android/getting-started.mdx
- __Type:__
- 📚Docs
- __Ticket:__ [ANDROID-1209](<https://issues.ustream-adm.in/browse/ANDROID-1209>), [ANDROID-1210](<https://issues.ustream-adm.in/browse/ANDROID-1210>)
Added a note for regional cluster users.
> docs(regional-cluster): android-1209 Note for regional cluster users

- src/pages/player-sdk-android/changing-tracks.mdx
- src/pages/player-sdk-android/development-process.mdx
- src/pages/player-sdk-ios/customization.mdx
- __Type:__
- 🐛Fix
There were small grammatical and other problems in the Player SDK docs.
Corrected the grammatical errors & typos.
> fix(player-sdks): Minor fixes after proof reading.

- src/data/nav-items.yaml
- src/pages/channel-api-channel-page-design/cover-image.mdx
> docs(channel): cover image

- src/data/nav-items.yaml
- src/pages/channel-api-chat.mdx
> docs(chat): turn on/off chat

- src/data/nav-items.yaml
- src/pages/channel-api-video-management/manage-audio-tracks.mdx
> docs(video): manage audio tracks

- src/pages/channel-api-qna.mdx
> docs(qna): check QnA is enabled / turn on/off QnA

- src/data/nav-items.yaml
- src/pages/channel-api-off-air-settings/manage-selected-videos.mdx
- src/pages/channel-api-off-air-settings/manage-slideshow.mdx
- src/pages/channel-api-off-air-settings/overview.mdx
> docs(off_air): off air settings

- src/data/nav-items.yaml
- src/pages/channel-api-caption-autopublish.mdx
> docs(channel): caption autopublish

- src/pages/channel-api-channel-page-design/cover-image.mdx
> docs(cover): heading fix

- src/pages/channel-api-channel-page-design/cover-image.mdx
- src/pages/channel-api-off-air-settings/manage-slideshow.mdx
> docs(channel): curl example for image upload

- src/pages/channel-api-video-management/manage-audio-tracks.mdx
> docs(video): default video language

- src/pages/channel-api-off-air-settings/manage-selected-videos.mdx
> doc(off_air): Set Selected Videos fix

- src/pages/player-api-usage.mdx
- __Type:__ 📚Docs
- __Ticket:__ [PLAY-258](https://issues.ustream-adm.in/browse/PLAY-258)
There were no events documented that would provide information about user|system initiated seeks happing.
> PLAY-258 document seekStarted/seekCompleted events

- src/pages/player-api-usage.mdx
- __Type:__ 📚Docs
- __Ticket:__ [PLAY-2163](<https://issues.ustream-adm.in/browse/PLAY-2163>)
There was no information  exposed through the Player API about autoplay being blocked.
The linked ticket contains the implementation in the documented manner.
> PLAY-2163 document autoplay rejected

- src/pages/player-sdk-android/changelog.mdx
- src/pages/player-sdk-android/development-process.mdx
- src/pages/player-sdk-android/using-plugins.mdx
- __Type:__
- 📚Docs
- __Ticket:__ [ANDROID-1307](<https://issues.ustream-adm.in/browse/ANDROID-1307>)
Added documentation for Android Player SDK 1.5.0
One minor lexical correction.
> Android playersdk 1.5.0 docs

- src/data/nav-items.yaml
- src/pages/channel-api-chat-2-0/export.mdx
- src/pages/channel-api-chat-2-0/initialization.mdx
- src/pages/channel-api-chat-2-0/moderators.mdx
- src/pages/channel-api-chat-2-0/rooms.mdx
- src/pages/channel-api-chat-2-0/settings.mdx
> docs(chat): Chat 2.0 docs

- src/pages/player-api-usage.mdx
- __Type:__
- 📚Docs
- __Ticket:__ [PLAY-2366](<https://issues.ustream-adm.in/browse/PLAY-2366>)
> fix(player-api-usage.mdx): play-2366 fix event listener descriptions

- src/data/nav-items.yaml
- src/pages/api-basics-rate-limits.mdx
- src/pages/channel-api-basic-channel-management.mdx
- src/pages/channel-api-events.mdx
- src/pages/channel-api-video-management/basic-video-management.mdx
- src/pages/channel-api-video-management/download-your-videos.mdx
- src/pages/channel-api-video-management/manage-captions.mdx
- src/pages/channel-api-video-management/manage-video-chapters.mdx
- src/pages/channel-api-video-management/upload-videos-new.mdx
- src/pages/channel-api-video-management/upload-videos.mdx
- src/pages/channel-api-watson-live-captioning.mdx
- __Type:__ ✨Feat
- __Ticket:__ [COBRA-3972](<https://issues.ustream-adm.in/browse/COBRA-3972>)
Currently, our customers have no information about rate limits
Add basic rate limits description
Add `429` Error response codes to rate-limited endpoints
> API Rate Limits

- src/data/nav-items.yaml
- src/pages/player-sdk-android/changelog.mdx
- src/pages/player-sdk-android/changing-tracks.mdx
- src/pages/player-sdk-android/development-process.mdx
- src/pages/player-sdk-android/getting-started.mdx
- src/pages/player-sdk-android/google-cast-support.mdx
- src/pages/player-sdk-android/migration-guide.mdx
- src/pages/player-sdk-android/pre-buffering.mdx
- src/pages/player-sdk-android/using-plugins.mdx
- __Type:__
- 📚Docs
Version 2.0.0 of Player SDK for Android is being released, needs documentation.
Add documentation for the Player SDK for Android v2.0.0
> Android player sdk 2.0.0

- src/pages/viewer-authentication-api-v2-getting-started.mdx
- __Type:__ 🐛Fix
- __Ticket:__  No
Some typo
> fix(viewer-authentication) fix typo

- src/pages/player-sdk-android/changelog.mdx
- src/pages/player-sdk-android/development-process.mdx
- __Type:__
- 📚Docs
- __Ticket:__ [ANDROID-1467](<https://issues.ustream-adm.in/browse/ANDROID-1467 >) & [ANDROID-1508](<https://issues.ustream-adm.in/browse/ANDROID-1508 >)
Upcoming release of Player SDK for Android v2.1.0 needs docs.
Update Player SDK for Android docs :)
> Android player sdk 2.1.0

- src/data/nav-items.yaml
- src/pages/channel-api-virtual-events/basics.mdx
- src/pages/channel-api-virtual-events/csv-export.mdx
- src/pages/channel-api-virtual-events/registration.mdx
- __Type:__
- 📚Docs
Virtual Events endpoints are not documented
Extended Channel API documentation with a Virtual Events section
> Add documentation for endpoints of virtual events

- src/data/nav-items.yaml
- src/pages/channel-api-video-management/replace-videos.mdx
- __Type:__
- ✨Feat
- __Ticket:__ [PROCORE-420](<https://issues.ustream-adm.in/browse/PROCORE-420>)
Implement Docs for Replacement API
Created replace-videos mdx file and added replace videos to the nav-items
> feat(channel-api): Implement video replacement API docs

- src/data/nav-items.yaml
- src/pages/broadcaster-sdk-android/aux-features.mdx
- src/pages/broadcaster-sdk-android/changelog.mdx
- src/pages/broadcaster-sdk-android/development-process.mdx
- src/pages/broadcaster-sdk-android/getting-started.mdx
- src/pages/broadcaster-sdk-android/migration-guide.mdx
- __Type:__
- 📚Docs
- __Ticket:__ [ANDROID-1639](<https://issues.ustream-adm.in/browse/ANDROID-1639>)
Android Broadcasters SDK 1.0.0 needs documentation.
Added the documentation.
> docs(android-broadcaster-sdk): android-1639 doc for Android BC SDK 1.0.0

- src/pages/player-sdk-android/changelog.mdx
- src/pages/player-sdk-android/changing-tracks.mdx
- src/pages/player-sdk-android/development-process.mdx
- src/pages/player-sdk-android/getting-started.mdx
- src/pages/player-sdk-android/google-cast-support.mdx
- src/pages/player-sdk-android/pre-buffering.mdx
- __Type:__
- 📚Docs
- __Ticket:__ [ANDROID-1710](<https://issues.ustream-adm.in/browse/ANDROID-1710>)
Updated documentation according to EU / WW Cluster changes
Updated documentation
> docs(public): android player-sdk 2.2.0 release

- src/pages/player-sdk-ios/changelog.mdx
- src/pages/player-sdk-ios/getting-started.mdx
- 📚Docs
Update docs for release 2.0.17
I have updated it :)
> docs(ios-player-sdk): documentation updated for release 2.0.17

- src/pages/player-api-usage.mdx
- 📚Docs
The new feature that allows you to toggle the visibility of the different components of the player, is not documented yet.
I documented it.
> docs(player-api-usage): document the new visibility toggling feature

- package-lock.json
- src/pages/broadcaster-sdk.mdx
- __Type:__
- ✨Feat
- __Ticket:__ [PROCORE-636](<https://issues.ustream-adm.in/browse/PROCORE-636>)
Adds Sunset message to the Broadcast SDK home page
> feat(broadcaster): display sunset message

- src/pages/broadcaster-sdk-android/aux-features.mdx
- src/pages/broadcaster-sdk-android/changelog.mdx
- src/pages/broadcaster-sdk-android/development-process.mdx
- src/pages/broadcaster-sdk-android/diagnosing-a-problem.mdx
- src/pages/broadcaster-sdk-android/getting-started.mdx
- src/pages/broadcaster-sdk-android/migration-guide.mdx
- src/pages/broadcaster-sdk-ios/authentication.mdx
- src/pages/broadcaster-sdk-ios/customization.mdx
- src/pages/broadcaster-sdk-ios/development-process.mdx
- src/pages/broadcaster-sdk-ios/diagnosing-a-problem.mdx
- src/pages/broadcaster-sdk-ios/getting-started.mdx
- src/pages/broadcaster-sdk.mdx
I messed up the broadcaster SDK message, need to update it again 🤷
> feat: update broadcaster SDK sunset message

- src/data/nav-items.yaml
- src/pages/channel-api-video-management/manage-audio-tracks.mdx
- src/pages/channel-api-watson-live-captioning.mdx
- __Type:__
- ♻️Chore
- __Ticket:__ [COBRA-7262](<https://issues.ustream-adm.in/browse/COBRA-7262>)
Change Watson related texts
> chore(product-rename): cobra-7262 Update Watson Live captioning on developers.video.ibm.com

- src/data/nav-items.yaml
- src/pages/channel-api-qna-2-0/export.mdx
- src/pages/channel-api-qna-2-0/get-started.mdx
- src/pages/channel-api-qna-2-0/initialization.mdx
- src/pages/channel-api-qna-2-0/moderators.mdx
- __Type:__
- ✨Feat
New Q&A version does not have API docs
Document Q&A v2 functionalities
> feat: add qna docs

- src/components/EmbedPlayer/Controls/basic.js
- src/components/EmbedPlayer/Controls/custom.js
- src/components/EmbedPlayer/Controls/index.module.scss
- src/components/EmbedPlayer/Modules/ExampleMedia.js
- src/components/EmbedPlayer/Modules/ExampleMedia.module.scss
- src/components/EmbedPlayer/Modules/LoadContent.js
- src/components/EmbedPlayer/Modules/LoadContent.module.scss
- src/components/EmbedPlayer/Modules/MediaSwitcher.js
- src/components/EmbedPlayer/Modules/Property.js
- src/components/EmbedPlayer/index.module.scss
- src/gatsby-theme-carbon/components/HeaderNav/HeaderNav.js
- src/pages/player-api-examples/basic-embed.mdx
- src/pages/player-api-examples/custom-ui.mdx
- src/pages/player-api-examples/dynamic-insertion.mdx
- src/pages/player-api-examples/fullscreen-functionality.mdx
- src/pages/player-api-examples/multiple-instances.mdx
- src/pages/player-api-examples/responsive-embed.mdx
- src/pages/player-api-url-parameters.mdx
- src/pages/player-api-usage.mdx
- __Type:__
- 🐛Fix
- __Ticket:__ [COBRA-7615]
responsive embed page displays blue loading screen
Recently we increased Carbon version. In that version css prefix changed, but we did not change it in our custom scss files.
I fixed it with using prefix variable.
I also changed expired embeds to a recent embed video or channel. 
- I changed button sizes from deprecated px or 'field' to 'md'.
- I changed wrong header aria label
- I changed deprecated handleClick to onClick in ClickableTile component
- I made some eslint fixes
> feat(embed-fixes): cobra-7605  responsive embed page displays blue loading screen

- package-lock.json
- package.json
- src/gatsby-theme-carbon/components/LeftNav/LeftNav.js
- __Type:__
-✨Chore
- __Ticket:__ [COBRA-7857](<https://issues.ustream-adm.in/browse/COBRA-7857>)
_Fix vulnerability in IBM/video-streaming-developer-docs_
Fixed some vulnerabilities by upgrading `gatsby-theme-carbon`
(It still uses gatsby 4)
I added 'inert' property because left menuitems were not clickable without it.
> COBRA-7857 Fix vulnerability in IBM/video-streaming-developer-docs

- src/pages/channel-api-video-management/replace-videos.mdx
- src/pages/channel-api-video-management/upload-videos-new.mdx
- __Type:__
- 📚Docs
- __Ticket:__ [IVSC-160](<IVSC-160>)
Percentage added to upload api response
> ivsc-160 Progress in upload status API endpoints

- src/components/EmbedPlayer/Modules/MediaSwitcher.js
- src/pages/player-api-examples/multiple-instances.mdx
- src/pages/player-api-examples/multiview.mdx
- src/pages/player-api-url-parameters.mdx
- src/pages/player-api-usage.mdx
- __Type:__
-✨Feat
- __Ticket:__ [IVSC-2181]
_Set up test LP channels_
> feat(channels): ivsc-2181 change demo channel

- src/data/nav-items.yaml
- src/pages/channel-api-video-management/scheduled-visibility-change.mdx
- __Type:__
- 📚Docs
Scheduled visibility change for videos via the API is not documented.
Added API documentation for scheduled visibility change.
> Create API documentation for scheduled video visibility change

- .whitesource
Reverts IBM/video-streaming-developer-docs#199
> Revert "Configure Mend for GitHub Enterprise"
