src/pages/channel-api-white-label-broadcasting/overview.mdx

Linking to Channel API White Label Broadcasting linkings in the CustomCards was broken.
Missing `withPrefix` func was added to CustomCards's href prop.

fix(white-label-broadcasting): customcard linking

---

gatsby-config.js

details:
https://www.gatsbyjs.org/docs/how-gatsby-works-with-github-pages/#deploying-to-the-root-subdomain-and-using-a-custom-domain

fix(gatsby-config): remove pathprefix

---

src/gatsby-theme-carbon/components/HeaderShadow.module.scss

Fixes #7 by adjusting the `height` to match the `line-height` and changing `display` to `table-cell`

fix: adjust mobile header alignment

---

src/pages/viewer-authentication-api-implementing-viewer-authentication.mdx

- __Type:__
- 🐛Fix
Clients are confused when their viewers don't show up in the viewer tracking. That's because the misleading "username" field in the example viewer auth implementation
Dropped the username, let users use "user" instead

fix(auth-api): promote user claim in the token instead of username

---

src/pages/viewer-authentication-api-hash-lifetime-and-expiration.mdx

- __Type:__
- 🐛Fix
For viewer auth adopters it's not always clear that the expiration should be in seconds, therefore they tend to use unix timestamp in milliseconds, that can lead to problems as we interpret this value as seconds.
Explicitly instruct users to use unix timestamp in seconds

fix(viewer-auth): expiration timestamp must be in seconds

---

gatsby-config.js
static/CNAME

- __Type:__
- ♻️Chore
Deploying to custom domain `developers.video.ibm.com`:
- remove `pathPrefix` from `gatsby-config.js`
- add CNAME to static
See Gatsby Docs:
https://www.gatsbyjs.com/docs/how-gatsby-works-with-github-pages/#deploying-to-the-root-subdomain-and-using-a-custom-domain

feat(custom-domain): deploying to custom domain

---

src/pages/channel-api-video-management/upload-videos.mdx

- __Type:__
- 🐛Fix
Looks like a typo in the Channel API page double `uploads` in the url.
Removed the second `uploads`

fix: channel api typo

---

src/pages/channel-api-broadcast-settings/broadcasting-devices.mdx

- __Type:__
-✨Fix
- __Ticket:__ [CORE-2638](<https://issues.ustream-adm.in/browse/CORE-2638>)
_Typo in "Broadcasting devices" API documentation_

feat(broadcasting-devices): core-2638 Typo in "Broadcasting devices" API

---

src/pages/player-api-usage.mdx

- __Type:__ 📚 Docs
- __Ticket:__ [PLAY-2164](https://issues.ustream-adm.in/browse/PLAY-2164)
Documentation of contentAvailable event was missing.

PLAY-2164 document contentAvailable event

---

package-lock.json
package.json

- __Type:__ ♻️ Chore
Web player api is out of date.
Update api to new minor version. ([1.2.0](https://github.com/IBM/video-streaming-web-player-api/releases/tag/v1.2.0))

update player api version to 1.1.0 -> 1.2.0

---

src/data/nav-items.yaml
src/pages/channel-api-video-management/upload-videos-new.mdx
src/pages/channel-api-video-management/upload-videos.mdx

- __Type:__
- 📚Docs
- Marking the old FTP upload deprecated and suggesting using the new video upload in the future.
- Added documentation for the new video upload method.

docs(channel): add docs for new video upload API

---

src/pages/player-sdk-ios/ad-integration.mdx

- __Type:__
- ✨Feat
- __Ticket:__ [IOS-1164](<https://issues.ustream-adm.in/browse/IOS-1164>)
iOS Player SDK Ad integration is no longer supported.
Added a deprecation alert to the related doc section.

feat(player-sdk): add deprecation notice to iOS ad integration

---

src/pages/viewer-authentication-api-implementing-viewer-authentication.mdx

- __Type:__
- 🐛Fix
The `$_GET` can be confusing in the viewer auth example. Users assume that they will get a `user` query parameter on their auth endpoint.
Using `$_SESSION` suggests, that they have to read their own user session, and pass back the user identifier in the token

fix: use session in the example instead of a query param

---

.github/workflows/deploy.yml
.travis.yml
README.md

- __Type:__
- 🛠Build
- ♻️Chore
- 📚Docs
- 📦Refactor
- 🚢Release
There was a critical vulnerability discovered in Travis CI recently - https://travis-ci.community/t/security-bulletin/12081 - and I think it's better to solve the CI/CD tasks entirely with Github Actions.
I removed the Travis related workflow files and docs.
I also created a workflow yml for Github Actions using the [Gatsby Publish](https://github.com/marketplace/actions/gatsby-publish) action.

feat(ci/cd): use github actions instead Travis

---

src/data/nav-items.yaml
src/pages/player-api-url-parameters.mdx
src/pages/player-api-usage.mdx

- __Type:__
- 📚Docs
- __Ticket:__ [PLAY-2487](<https://issues.ustream-adm.in/browse/PLAY-2487>)
Extend documentation with new URL Params
Outsource URL Parameters from Embed API Usage docs
Documentation

PLAY-2487 New params and outsourcing Params to separate page

---

src/pages/player-api-url-parameters.mdx

- __Type:__
- 📚Docs
- 🐛Fix
The src in the Example contained malformed url which had an older, unused parameter left in it
did cleanup on the parameter list
checked the url

docs(player url parameters): fix example url

---

src/pages/player-api-url-parameters.mdx

- __Type:__
- 📚Docs
- __Ticket:__ [PLAY-2527](https://issues.ustream-adm.in/browse/PLAY-2527)
There is a new query parameter available for the web Player which is not yet documented
Added the parameter, short description, value range and default value to the last row of the URL parameter table
--

update player-api-url-parameters with new param

---

src/pages/player-api-usage.mdx

- __Type:__ ✨Feat
- __Ticket:__ PLAY-2541
There is no current way for our users to go fullscreen on iOS, because on iOS only $video.webkitEnterFullscreen is supported and it opens the default video UI.
Add new `webkitEnterFullscreen` command.
Add new `webkitEnterFullscreenRejected` event for covering cases when the browser prevents this action.

PLAY-2541 document webkitEnterFullscreen

---

src/pages/player-api-examples/fullscreen-functionality.mdx

- __Type:__ 🐛Fix
- __Ticket:__ PLAY-2109
In the fullscreen example we had the built in fullscreen button, but its state didn't update with  the custom fullscreen functionality.
I used the new hideFullscreen param to hide the built-in button.

PLAY-2109 remove fullscreen button

---

.github/dco.yml

- __Type:__
- ✨Feat
Right now DCO checks not let merge commits that contains commit messages which are not signed.
It is possible to disable the check for commits authored and [signed](https://help.github.com/articles/signing-commits-using-gpg/) by members of the organization the repository belongs to. I added a DCO config yml where i switched off the check for members.

feat: disable signed commit messages check for IBM org members

---

src/pages/player-api-url-parameters.mdx

This change only contains 1 added parameter to the table of Player URL Parameters. The new loop parameter is already released to GA.
- __Type:__
- 📚Docs
- __Ticket:__ [PLAY-2648](<https://issues.ustream-adm.in/browse/PLAY-2648>)
People wanted to play their embed videos looped
Tell them the magical url parameter with which they can achieve their goal: ?loop

docs: add "loop" to the list of query params

---

src/pages/channel-api-custom-metadata/channel-metadata-values.mdx
src/pages/channel-api-custom-metadata/video-metadata-values.mdx

- __Type:__
- ✨Feat
Setting values of different types of custom meta is not necessarily intuitive without documentation
Added docs and example request bodies for each available data type so clients can understand more what the expected request formats are

feat: extend custom meta values docs with data types

---

.github/workflows/deploy.yml

- __Type:__
- ♻️Chore
- __Ticket:__ [cobra-5554](<https://issues.ustream-adm.in/browse/cobra-5554>)
Current Github actions workflow is not allowed for deploy.
I changed it to be IBM compatible.
Replace Watson Media to IBM Video Streaming at Product Portfolio link.

chore(deploy): use allowed workflow for deploy

---

.github/.dependabot.yml

- __Type:__
- ♻️Chore
- __Ticket:__ [cobra-7554]
We can't update gatsby dependency yet to version 5, because gatsby-theme-carbon is not yey compatible with it
I added a depandabot rule to ignore gatsby package

chore(dependabot): cobra-7554 add ignore rule for gatsby

---

src/pages/channel-api-video-management/download-your-videos.mdx

- __Type:__
- ✨Feat
- __Ticket:__ [COBRA-7574]
We extended the download expiration time from 24 hours to 365 days
We changed the 'You have 24 hours to download the video file' to 'You have 365 days to download the video file

feat(video-download): cobra-7574 extend download expiration

---

src/pages/channel-api-video-management/basic-video-management.mdx

- __Type:__
- ✨Feat
Filter docs already added to user videos, but no docs for channels video filtering.
Added docs to channels videos too

feat(channels): add docs to channel video filtering

---

src/pages/channel-api-video-management/basic-video-management.mdx

- __Type:__
- 🐛Fix
Pager docs of user/videos and channel/videos is not accurate
Show proper paging examples

fix(videos): adjust paging response examples
